global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'minha-app'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.docker.internal:3000']

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

rule_files:
  - '/etc/prometheus/alerts.rules.yml'